# Generated by Django 5.0.1 on 2024-07-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donghonam',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='donghonam',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='donghonam',
            name='color',
        ),
        migrations.RemoveField(
            model_name='donghonam',
            name='filter_price',
        ),
        migrations.RemoveField(
            model_name='donghonamimages',
            name='donghonam',
        ),
        migrations.DeleteModel(
            name='DonghonamTag',
        ),
        migrations.DeleteModel(
            name='Donghonam',
        ),
        migrations.DeleteModel(
            name='DonghonamImages',
        ),
    ]
